### ISSUE TITLE
ph803w to MQTT

### ISSUE THREAD

**Issue by cellerich** [Apollon77/node-ph803w#1]
Hi Ingo

Hope you don’t mind that I took your base code and added a quick and dirty way to interface with Home Assistant trough MQTT.
My repo is here [https://github.com/cellerich/ph803w_2_mqtt](https://github.com/cellerich/ph803w_2_mqtt).

There is also a “ready to use” docker image on docker hub.

**Comment by Apollon77** [comment]
PS: And in fact you code just adds a main.js with the mqtt logix and uses the library ... so why copy it ? Just reference my lib in your package.json and use it - then you do not need to copy my stuff over

**Comment by cellerich** [comment]
As I mentioned, it’s just a quick and dirty way to bring the data to MQTT. I made the docker container for a friend in Ko Samui who wants to monitor his pool values. 
I do not have a device here to test and debug, so it was the easiest approach.

When did you release your library, yesterday?

If I find time next time I visit Samui I might refactor my code and use your library. Thanks again for your effort you put into reverse engineering!

**Comment by Apollon77** [comment]
> When did you release your library, yesterday?

yes and also iterated on it a lot yesterday :-)
But should be stable-ish for now
